- hosts: localhost
  become: yes
  tasks:
    - name: Update OS
      apt:
        update_cache: yes

    - name: Install Docker
      apt:
        name: docker.io
        state: present

    - name: Ensure Docker running
      service:
        name: docker
        state: started
        enabled: yes
